# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-shield" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "97ea7027cc9a75d9b43f5ef404041d010ad8061fd4e449a474bf718482312eba"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bab59297694e7e5c22daf650122fef6594ff22eea40b023c6b83e22c9256fc54"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db179dff7432521b9009f5541c8eef10e975c6da24933f3c52acc48cfcea578c"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "137e398eb1fef3db176439faf690433c24f576dc1d1d05e35966b2a01c7c127a"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kube-shield"
  desc "Kubernetes Security Posture Manager"
  homepage "https://github.com/RamazanKara/kube-shield"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-shield"
  generate_completions_from_executable "bin/kube-shield", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
