# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-shield" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "e0e35849f4930d036b71a5e0c99c97249ddcb825491e67957879f260acf2c9b5"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3c44c81914911b43055e03249e9cb52aa9e8c4b94cb7ba1854f549a738dbe5c7"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "321532031db6822bb0b455a2267500542de10423576a53f1c93c3b951abc32c9"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4de1843bdd4f98bc5a780ddb9d4c249e840889cdaa181797243e040e93db7345"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kube-shield"
  desc "Kubernetes Security Posture Manager"
  homepage "https://github.com/RamazanKara/kube-shield"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-shield"
  generate_completions_from_executable "bin/kube-shield", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
