# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-shield" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "15bc5f6adcea2c83943dcb6f178b0fb41b93c5b91da53f9838ae84157c3244d6"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f032f4a2acce5e4b2584d2ba4578642973d6c8736b343f378934e432fe44d528"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "71c620848ee8fe1748000a30df811eb467a145a4ce2391bbd8821f3bd6e98025"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f2d9864c70fe63053e0a29b6ba57a00a11a76c3b4d3416593f0c645ca510f72"
      url "https://github.com/RamazanKara/kube-shield/releases/download/v#{version}/kube-shield_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kube-shield"
  desc "Kubernetes Security Posture Manager"
  homepage "https://github.com/RamazanKara/kube-shield"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-shield"
  generate_completions_from_executable "bin/kube-shield", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
